"""empty message

Revision ID: 2b285c4d70e9
Revises: 9f80ecd21922
Create Date: 2021-08-02 08:27:49.142189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b285c4d70e9'
down_revision = '9f80ecd21922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_execl', sa.Column('ImageName', sa.String(length=128), nullable=True))
    op.drop_column('t_execl', 'PONumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_execl', sa.Column('PONumber', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('t_execl', 'ImageName')
    # ### end Alembic commands ###
